name: Android Build Release Workflow

on:
  workflow_dispatch:
    branches: [Development]
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+([0-9]+)'

env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN_MYAPP_ANDROID }}
  APP_NAME: 'MyApp-Android/ENV_TEST'
  TESTING_GROUP: 'ENV_TEST'
  UPLOAD_FILE: '.android/app/build/outputs/apk/debug/app-debug.apk'
  JAVA_HOME_9.0.4_x64: /opt/hostedtoolcache/jdk/9.0.4/x64
  JAVA_HOME: /opt/hostedtoolcache/jdk/9.0.4/x64
  JAVA_HOME_9_0_4_X64: /opt/hostedtoolcache/jdk/9.0.4/x64
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
   
      - name: Use GitHub Workspace
        run: echo "GitHub Workspace: ${{ github.workspace }}"

    - name: Run a Command in the Workspace
      run: |
        cd ${{ github.workspace }}
        # Your command goes here
      

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: App
          path: ${{ github.workspace}} .android/app/build/outputs/apk/debug/app-debug.apk'
      - name: upload artefact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ronakukani/Github-Actions-Demo
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Testers
          file: app/build/outputs/apk/release/app-release.apk
          notifyTesters: true
          debug: false
          releaseNotes: "here is your release note"
