name: Deploy-Android-TEST

on:
  workflow_dispatch:
    branches: [Development]
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+([0-9]+)'

env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN_MYAPP_ANDROID }}
  APP_NAME: ${{ 'MyApp-Android/ENV_TEST' }}
  TESTING_GROUP: ${{ 'ENV_TEST' }}
  UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/app-release.apk' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run Yarn Install
        run: |
             cd Home-Flavours-GIT
             cd ./packages/app-mobile/
             npm i -g corepack
             yarn install             
      - name: Build application
        run: |
             cd Home-Flavours-GIT
             cd ./android
             chmod +x gradlew
             ./gradlew assembleDebug             
      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 3

      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          group: Developer
          file: ${{ env.UPLOAD_FILE }}
          debug: true
