name: Deploy-Android-TEST8989

on:
  workflow_dispatch:
    branches: [Development]
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+([0-9]+)'

env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN_MYAPP_ANDROID }}
  APP_NAME: ${{ 'MyApp-Android/ENV_TEST' }}
  TESTING_GROUP: ${{ 'ENV_TEST' }}
  UPLOAD_FILE: ${{ './android/app/build/outputs/apk/debug/app-debug.apk' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Checkout direct
        run: |
             cd Home-Flavours-GIT
             ls -l
             
      - name: Install App Center CLI
        run: npm install -g appcenter-cli    

      - name: Authenticate with App Center
        run: appcenter login --token f5af3da87aea380656d92e1f0412acbfc5a3f059 --quiet

        
      - name: Upload to App Center
        run: appcenter distribute release --app G8-HomeFlavours/HomeFlavours --group internal --file ${{ env.UPLOAD_FILE }}
