name: Deploy-AndExpo1223

on:
  workflow_dispatch:
    branches: [Development]
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+([0-9]+)'

env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN_MYAPP_ANDROID }}
  APP_NAME: 'MyApp-Android/ENV_TEST'
  TESTING_GROUP: 'ENV_TEST'
  UPLOAD_FILE: '.android/app/build/outputs/apk/debug/app-debug.apk'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Set up Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64

      - name: Install Yarn
        run: |
          npm install -g yarn
          yarn install
          
      - name: Build Android app
        uses: expo/expo-github-action@v5
        with:
          expo-version: '4.x'  # Adjust the version as needed
          expo-token: ${{ secrets.EXPO_CLI_TOKEN }}
          node-version: '14'  # Match with the Node.js version used above
          working-directory: Home-Flavours-GIT  # Adjust this based on your project's directory structure

      - name: List APK files
        run: ls -R Home-Flavours-GIT/
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload build to App Center
        uses: actions/upload-artifact@v2
        with:
          name: app-build
          path: ${{ env.UPLOAD_FILE }} # Adjust this based on your project's build output directory

      - name: Install App Center CLI
        run: npm install -g appcenter-cli

      - name: Authenticate with App Center
        run: appcenter login --token ${{ secrets.APP_CENTER_TOKEN }} --disable-telemetry

      - name: Distribute build to App Center
        run: appcenter distribute release --app ${{ secrets.APP_NAME }} --group Developer --file ${{ env.UPLOAD_FILE }} # Adjust this based on your project's build file path
